version: 2

sources:
# 0. Dim datasets (stock prices, news headlines) ingested into our GCP project via Meltano
  - name: dim
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: "mag7_intel_dims"
    tables:
      - name: dim_ticker
      - name: dim_calendar

# 1. Raw datasets (stock prices, news headlines) ingested into our GCP project via Meltano
  - name: raw
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: "{{ env_var('BQ_DATASET_RAW') }}"
    tables:
      - name: stock_prices_all
      - name: news_headlines

# 2. BQ public datasets (GDELT gkg)
  - name: gdeltv2
    database: gdelt-bq            # GCP project that hosts GDELT
    schema: gdeltv2
    tables:
      - name: gkg_partitioned
      - name: events

  # 3. Staging Dataset (typed & cleaned staging tables)
  - name: staging
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: "{{ env_var('BQ_DATASET_STAGING') }}"
    tables:
      - name: stock_prices_mag7     # stocks & indexes
      - name: stock_prices_vix
      - name: news_gkg
      - name: news_headlines

# 4. Intermediate Dataset (joined, enriched tables)
#  - name: intermediate
#    database: "{{ env_var('GCP_PROJECT_ID') }}"
#    schema: "{{ env_var('BQ_DATASET_INTERMEDIATE') }}"
#    tables:
#      - name: stock_prices_mag7_ta
#      - name: index_benchmark_join
#      - name: sa

# 5. Mart Dataset (fcts, dims)
