version: 2

sources:
# raw datasets (stock prices, news headlines) ingested into our GCP project via Meltano
  - name: raw
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: "{{ env_var('BQ_DATASET_RAW') }}"
    tables:
      - name: stock_prices_all
      - name: news_headlines

# public datasets (GDELT)
  - name: gdeltv2
    database: gdelt-bq            # GCP project that hosts GDELT
    schema: gdeltv2
    tables:
      - name: gkg_partitioned
      - name: events
