version: 2

sources:

  - name: raw
    database: "{{ env_var('GCP_PROJECT_ID') }}"
#    schema: mag7_intel_raw
    schema: "{{ env_var('BQ_DATASET_RAW') }}"
    tables:
      - name: stock_prices
      - name: google_news

  - name: public_gdelt
    database: gdelt-bq
    schema: gdeltv2
    tables:
      - name: events
