version: 2

seeds:
  - name: tickers
    description: "Static metadata for MAG7 tickers."
    columns:
      - name: ticker
        tests:
          - not_null
          - unique

  - name: calendar
    description: "Calendar from 2020-01-01 to 2030-12-31 with holidays."
    columns:
      - name: date
        tests:
          - not_null
          - unique
