version: 2

models:
  - name: stg_stock_prices
    description: "Staging table for stock prices: typed, deduplicated by (ticker, trade_date), incremental on fetched_at."
    columns:
      - name: ticker
        description: "Stock ticker symbol (e.g. AAPL, MSFT)."
        tests:
          - not_null

      - name: trade_date
        description: "Trading date for the price (DATE)."
        tests:
          - not_null

      - name: open
        description: "Opening price for the trading day."
      - name: high
        description: "Highest price for the trading day."
      - name: low
        description: "Lowest price for the trading day."
      - name: close
        description: "Closing price for the trading day."
      - name: adj_close
        description: "Adjusted closing price for the trading day."
      - name: volume
        description: "Number of shares traded during the day."

      - name: fetched_at
        description: "Timestamp when this record was fetched/scraped into the raw layer, used as incremental watermark."

  - name: stg_google_news
    description: "Staging table for Google News headlines: typed, deduplicated by (ticker, news_ts), incremental on fetched_at."
    columns:
      - name: ticker
        description: "Stock ticker symbol associated with the news item."
        tests:
          - not_null

      - name: headline
        description: "News headline text."

      - name: news_ts
        description: "Timestamp when the news article was originally published or timestamped by the source."
        tests:
          - not_null

      - name: url
        description: "URL of the news article."
      - name: source
        description: "Source/publisher of the news article (e.g. Reuters, Bloomberg)."
      - name: window
        description: "Ingestion window or lookback period label used when collecting this article (e.g. 1d, 7d)."

      - name: fetched_at
        description: "Timestamp when this article was fetched/scraped into the raw layer, used as incremental watermark."
        tests:
          - not_null

      - name: sentiment_label
        description: "Discrete sentiment label assigned to the article (e.g. positive, neutral, negative)."
      - name: sentiment_score
        description: "Continuous sentiment score for the article (e.g. from a FinBERT model)."
